package com.pilates.app.model;

public enum ActionType {

    ICE_EXCHANGE,
    OFFER,
    ANSWER,
    TRAINEES,
    TRAINERS,
    ADD_TRAINER,
    REMOVE_TRAINER,
    ADD_TRAINEE,
    REMOVE_TRAINEE,
    CONNECT,
    CONNECT_TO,
    INIT_TRAINER,
    INITIALIZED,
    CALL_IN_PROGRESS,
    STOP_COMMUNICATION,
    NEXT,
    TRAINEE_LEAVED,
    ON_HOLD,
    SWITCHED,
    STATS,
    CLASS_STARTED,
    CLASS_NOT_STARTED,
    TRY_JOIN_CLASS,
    CLASS_NOT_EXISTS,

    OFFER_RECEIVED
}
